import {
  StatItem,
  MissionPillar,
  RoadmapPhase,
  FocusCard,
  PlatformFeature,
  IngestionVector,
  ComplianceBadge,
  IntelDispatch,
} from './types';

export const STATS_DATA: StatItem[] = [
  {
    id: 'gpi',
    value: '142nd',
    numericValue: 142,
    suffix: 'nd',
    label: 'GLOBAL PEACE INDEX RANK',
    description: 'Sub-Saharan civilian safety index critical urgency zone',
  },
  {
    id: 'lives',
    value: '10,000+',
    numericValue: 10000,
    suffix: '+',
    label: 'LIVES LOST ANNUALLY',
    description: 'Preventable regional civilian casualties and kidnappings',
  },
  {
    id: 'spend',
    value: '$3.86B',
    prefix: '$',
    numericValue: 3.86,
    suffix: 'B',
    label: 'ANNUAL SECURITY BUDGET',
    description: 'Trapped in siloed, reactive legacy security measures',
  },
  {
    id: 'users',
    value: '96.27M',
    numericValue: 96.27,
    suffix: 'M',
    label: 'ACTIVE SMARTPHONE USERS',
    description: '96.27 million Nigerians currently unprotected by real-time sovereign alert networks',
  },
];

export const MISSION_PILLARS: MissionPillar[] = [
  {
    title: 'DETECT',
    monoCode: 'PROTOCOL.01 // MULTI-SOURCE SENSING',
    description: 'Multimodal ground, aerial, satellite, and civilian telemetry capturing threats at acoustic, optical, and sensor levels.',
  },
  {
    title: 'ANALYZE',
    monoCode: 'PROTOCOL.02 // AUTONOMOUS MULTI-VECTOR FUSION',
    description: 'Security intelligence driven by our custom proprietary software — fusing and sorting multimodal orbital, aerial, acoustic, OSINT, and civilian streams into verified tactical consensus in under 320ms.',
  },
  {
    title: 'RESPOND',
    monoCode: 'PROTOCOL.03 // TACTICAL DISPATCH',
    description: 'Sub-second encrypted routing directly to verified community defenders, medical units, and vetted rapid responders.',
  },
];

export const INGESTION_VECTORS: IngestionVector[] = [
  {
    id: 'vec-sat',
    title: 'Orbital Satellite & SAR Feeds',
    code: 'INTEL.SAT // LEO IMAGERY',
    tagline: 'High-altitude optical & synthetic aperture radar penetration',
    description: 'Persistent low-earth orbit satellite imagery analyzing remote forest encampments, unmapped transit tracks, and border movements.',
    africanContext: 'Breaks through heavy Harmattan dust hazes and equatorial cloud covers where standard aerial vision fails across the Sahel and Niger Delta.',
    protocolSpecs: 'Multi-spectral SAR edge processing · Sub-meter resolution change detection · 15-min revisit intervals',
    iconName: 'Satellite',
    status: 'CALIBRATING',
  },
  {
    id: 'vec-uav',
    title: 'Tactical Recon Drones (UAV)',
    code: 'INTEL.UAV // LONG-RANGE PATROL',
    tagline: 'Autonomous aerial overwatch across vulnerable transit corridors',
    description: 'Fixed-wing and multi-rotor long-range unmanned aerial vehicles monitoring high-risk transit arteries and rural agricultural belts.',
    africanContext: 'Automated patrols over known ambush arteries (Abuja-Kaduna, Benin-Ore, Port Harcourt-Aba, and interstate forest fringes) ahead of civilian convoys.',
    protocolSpecs: 'Thermal FLIR night-vision · 60km operational radius · Solar-assisted autonomous docking stations',
    iconName: 'Plane',
    status: 'ACTIVE',
  },
  {
    id: 'vec-nano',
    title: 'Urban Nano-Drones',
    code: 'INTEL.NANO // CLOSE-QUARTERS OVERWATCH',
    tagline: 'Pocket-deployable silent scouts for dense settlements',
    description: 'Ultra-miniaturized silent micro-drones designed for rapid tactical scouting in high-density urban compounds and tight alleyways.',
    africanContext: 'Navigates dense unplanned settlements, market labyrinths, and enclosed compounds to locate trapped civilians without generating acoustic alert.',
    protocolSpecs: 'Sub-35g airframe · Micro-optics obstacle avoidance · Low-RF stealth communication link',
    iconName: 'Drone',
    status: 'CALIBRATING',
  },
  {
    id: 'vec-cctv',
    title: 'Solar Edge CCTV & AI Optics',
    code: 'INTEL.OPTIC // GRID-INDEPENDENT VISION',
    tagline: 'Self-powered smart camera nodes at strategic transit chokepoints',
    description: 'Solar-powered optical nodes equipped with on-device computer vision for license plate recognition, roadblock detection, and perimeter anomalies.',
    africanContext: 'Operates 100% off-grid using dedicated solar capacitors, unaffected by local municipal power outages (NEPA/grid collapse).',
    protocolSpecs: 'Edge-AI neural inference · Zero-bandwidth sleep mode · Tamper-resistant physical casing',
    iconName: 'Camera',
    status: 'ACTIVE',
  },
  {
    id: 'vec-acoustic',
    title: 'Acoustic Gunshot & Blast Nodes',
    code: 'INTEL.AUDIO // BALLISTIC TRIANGULATION',
    tagline: 'Instant muzzle blast and kinetic shockwave classification',
    description: 'Acoustic sensor arrays mounted on solar streetlights and community towers that isolate weapon discharge signatures within milliseconds.',
    africanContext: 'Distinguishes between celebratory fireworks/generators and actual assault rifle discharge (AK-47/7.62mm signatures) across sprawling neighborhoods.',
    protocolSpecs: 'Acoustic time-of-arrival triangulation · &lt; 80ms classification latency · 3D vector calculation',
    iconName: 'Mic',
    status: 'ACTIVE',
  },
  {
    id: 'vec-mesh',
    title: 'Offline LoRa & Bluetooth Mesh',
    code: 'INTEL.MESH // ZERO-INTERNET RELAY',
    tagline: 'Peer-to-peer radio hopping when cellular grids are jammed or down',
    description: 'Decentralized ad-hoc radio networking passing encrypted distress signals from device to device without relying on internet service providers.',
    africanContext: 'Guarantees life-saving data packet delivery in deep forest reserves, remote villages, or during intentional telecommunication shutdowns.',
    protocolSpecs: 'Long-Range (LoRa 868/915MHz) · BLE store-and-forward · Cryptographic multi-hop integrity',
    iconName: 'Radio',
    status: 'ACTIVE',
  },
];

export const ROADMAP_DATA: RoadmapPhase[] = [
  {
    id: 'phase-0',
    phase: 'PHASE 0 — NOW',
    timeframe: 'CURRENT ACTIVE PHASE',
    status: 'ACTIVE',
    title: 'Core Multimodal Architecture Validation',
    milestones: [
      'Brain³ OS Threat Ingestion Adapters',
      'Satellite & Drone Telemetry Ingestion API',
      'Encrypted Edge MVP Engineering',
    ],
  },
  {
    id: 'phase-1',
    phase: 'PHASE 1 — Q2 2025',
    timeframe: 'UPCOMING',
    status: 'UPCOMING',
    title: 'Private Beta Launch — Port Harcourt',
    milestones: [
      '1,000 Early Civilian Nodes',
      'Solar CCTV & Community Pilot Corridors',
      'Shielded Multi-Source Alert System Live',
    ],
  },
  {
    id: 'phase-2',
    phase: 'PHASE 2 — Q4 2025',
    timeframe: 'UPCOMING',
    status: 'UPCOMING',
    title: 'SOC2 Compliance + Tactical Drone Fleet Sync',
    milestones: [
      'Automated UAV Patrol Integrations',
      'Enterprise & Transit Fleet Licensing',
      'ISO 27001 Certified Security Operations',
    ],
  },
  {
    id: 'phase-3',
    phase: 'PHASE 3 — 2026',
    timeframe: 'UPCOMING',
    status: 'UPCOMING',
    title: 'Pan-African Expansion — 500,000 Nodes',
    milestones: [
      'Nigeria · Ghana · Kenya · Cameroon · DRC',
      'Regional Defense & Humanitarian Sat-Mesh',
      'Cross-Border Corridor Protection Matrix',
    ],
  },
];

export const FOCUS_CARDS: FocusCard[] = [
  {
    id: 'focus-1',
    number: 'SYS.MOD 01',
    title: 'Multimodal Ingestion Architecture',
    body: 'Building the unified encrypted relay infrastructure that ingests satellite imagery, aerial drone overwatch, edge CCTV, and civilian reports with shielded identity protection for reporters.',
    tags: ['AES-256 GCM', 'Custom Proprietary Core', 'Multi-Sensor Fusion'],
  },
  {
    id: 'focus-2',
    number: 'SYS.MOD 02',
    title: 'Autonomous Multi-Vector Threat Intelligence',
    body: 'Engineering custom proprietary software to fuse asynchronous satellite SAR, aerial UAV thermal feeds, acoustic gunshot arrays, and civilian reports. It filters noise, resolves African vernaculars, and sorts kinetic threats with sub-second precision.',
    tags: ['Proprietary AI Engine', 'Multimodal Stream Tokenizer', 'Vernacular Deconfliction', 'Kinetic Threat Sorter'],
  },
  {
    id: 'focus-3',
    number: 'SYS.MOD 03',
    title: 'Resilient Edge & Offline Mesh',
    body: 'Core mobile and hardware node engineering — shielded SOS alerts, low-bandwidth satellite fallback, encrypted evidence vault, and peer-to-peer LoRaWAN/BLE mesh hopping during telecom outages.',
    tags: ['LoRaWAN & BLE Mesh', 'Sub-3s Dispatch', 'Evidence Vault'],
  },
];

export const PLATFORM_FEATURES: PlatformFeature[] = [
  {
    id: 'feat-1',
    number: '01',
    title: 'Shielded Civilian Intelligence',
    description: 'Verified securely on Orbital while completely shielding reporter identity from recipients and the public to prevent reprisal.',
    technicalSpecs: 'Encrypted relay protocol: Orbital verifies identity internally while broadcasting anonymized danger vectors to recipients and responders.',
    category: 'CIVILIAN MESH',
    sourceType: 'CIVILIAN_TELEMETRY',
    badge: 'SHIELDED IDENTITY',
  },
  {
    id: 'feat-2',
    number: '02',
    title: 'Satellite & SAR Orbital Imagery',
    description: 'Persistent LEO satellite passes tracking remote hideouts, unmapped tracks, and corridor activity through dust and clouds.',
    technicalSpecs: 'Sub-meter multi-spectral optical & SAR radar feeds downlinked directly to Brain³ OS for automated spatial anomaly detection.',
    category: 'SATELLITE & UAV',
    sourceType: 'SATELLITE',
    badge: 'ORBITAL CONSTEL',
  },
  {
    id: 'feat-3',
    number: '03',
    title: 'Autonomous UAV & Drone Overwatch',
    description: 'Tactical long-range drones conducting automated route clearance ahead of civilian transit convoys.',
    technicalSpecs: 'Thermal FLIR sensors, 60km operational radius, encrypted video stream, and geofenced patrol loops synchronized via Brain³ OS.',
    category: 'SATELLITE & UAV',
    sourceType: 'DRONE',
    badge: 'AERIAL RECON',
  },
  {
    id: 'feat-4',
    number: '04',
    title: 'Urban Micro & Nano-Drone Scouting',
    description: 'Silent pocket-deployable nano-drones for close-quarters reconnaissance in dense settlements and compounds.',
    technicalSpecs: 'Ultra-low acoustic profile (&lt;18dB at 3m), real-time indoor lidar collision avoidance, low-RF telemetry link.',
    category: 'SATELLITE & UAV',
    sourceType: 'NANODRONE',
    badge: 'NANO TACTICAL',
  },
  {
    id: 'feat-5',
    number: '05',
    title: 'Solar-Powered Smart Edge CCTV',
    description: 'Grid-independent computer vision nodes at transit bottlenecks and community gates monitoring ambush setups.',
    technicalSpecs: '100% solar + supercapacitor backup. Edge neural inference streaming object detections to Brain³ OS without municipal power.',
    category: 'CCTV & SENSORS',
    sourceType: 'CCTV',
    badge: 'OFF-GRID VISION',
  },
  {
    id: 'feat-6',
    number: '06',
    title: 'Acoustic Gunshot Triangulation',
    description: 'Streetlight-mounted audio sensor arrays instantly classifying ballistic caliber and precise point of origin.',
    technicalSpecs: 'Multi-microphone acoustic time-difference array. Distinguishes AK-47 muzzle reports within 80ms, indexed into Brain³ spatial token map.',
    category: 'CCTV & SENSORS',
    sourceType: 'ACOUSTIC',
    badge: 'BALLISTIC AUDIO',
  },
  {
    id: 'feat-7',
    number: '07',
    title: 'Offline LoRa & BLE Mesh Relay',
    description: 'Peer-to-peer data hopping that routes critical SOS signals across devices when cellular towers fail or are sabotaged.',
    technicalSpecs: 'LoRa 868/915MHz long-range packet broadcasting + BLE store-and-forward routing between vehicles and phones directly to Brain³ OS edge nodes.',
    category: 'AI & INFRASTRUCTURE',
    sourceType: 'MESH_RELAY',
    badge: 'ZERO INTERNET',
  },
  {
    id: 'feat-8',
    number: '08',
    title: 'AI-Powered Brain³ OS',
    description: 'Our proprietary AI-powered OS Brain³. Fuses and sorts multimodal signals, resolves local dialects and slang, and weeds out rumors in real time.',
    technicalSpecs: 'Spatial-temporal neural transformer with African dialect tokenizers (Pidgin/Hausa/Yoruba/Igbo/French/Swahili), multi-source threat sorting, and < 320ms consensus.',
    category: 'AI & INFRASTRUCTURE',
    badge: 'AI-POWERED BRAIN³ OS',
  },
  {
    id: 'feat-9',
    number: '09',
    title: 'Live Geospatial Threat Heatmap',
    description: 'Real-time multi-source threat fusion mapping danger zones across street, city, and interstate corridors sorted by kinetic urgency.',
    technicalSpecs: 'Brain³ spatial clustering with sub-meter coordinate obfuscation, dynamic Voronoi safety corridors, and predictive trajectory AI.',
    category: 'AI & INFRASTRUCTURE',
    badge: 'NEURAL MAPPING',
  },
  {
    id: 'feat-10',
    number: '10',
    title: 'One-Touch Distress SOS Dispatch',
    description: 'Emergency signal with encrypted location and sensor vector dispatched to verified responders in under 3 seconds.',
    technicalSpecs: 'Hardware button trigger override with cellular, satellite fallback, SMS burst, and mesh relaying executed via Brain³ OS deterministic bus.',
    category: 'TACTICAL DISPATCH',
    badge: 'SUB-3S ROUTE',
  },
  {
    id: 'feat-11',
    number: '11',
    title: 'Encrypted Evidence & Tamper Vault',
    description: 'Cryptographically sealed photo, audio, and video capture for indisputable human rights and legal documentation.',
    technicalSpecs: 'Military-grade 256-bit encryption, immutable timestamping, and decentralized hash verification verified on Brain³ OS ledger.',
    category: 'AI & INFRASTRUCTURE',
    badge: 'VERIFIED CHAIN',
  },
  {
    id: 'feat-12',
    number: '12',
    title: 'GSM Base-Station Anomaly Radar',
    description: 'Monitors cellular tower handoff irregularities and RF jamming attempts that precede coordinated attacks.',
    technicalSpecs: 'Passive cellular tower signal analysis detecting sudden base-station blackouts and illegal IMSI-catcher towers.',
    category: 'CCTV & SENSORS',
    sourceType: 'CELLULAR_GSM',
    badge: 'RF DEFENSE',
  },
];

export const COMPLIANCE_BADGES: ComplianceBadge[] = [
  {
    id: 'comp-1',
    title: 'SOC 2 TYPE II',
    status: 'IN PROGRESS',
    standardType: 'AUDIT VERIFICATION',
    description: 'Rigorous controls for security, availability, processing integrity, and privacy across all sensor relays.',
  },
  {
    id: 'comp-2',
    title: 'ISO 27001',
    status: 'PLANNED',
    standardType: 'SECURITY MANAGEMENT',
    description: 'Systematic information security management system framework adherence for multimodal data pipelines.',
  },
  {
    id: 'comp-3',
    title: '256-BIT AES ENCRYPTION',
    status: 'ARCHITECTURE STANDARD',
    standardType: 'CRYPTOGRAPHIC CORE',
    description: 'Military-grade cipher protecting data at rest, in transit, and across all drone, satellite, and mesh relays.',
  },
  {
    id: 'comp-4',
    title: 'GDPR & NDPR ALIGNED',
    status: 'DESIGN PRINCIPLE',
    standardType: 'DATA PRIVACY',
    description: 'Strict citizen rights protection, zero superfluous data ingestion, ephemeral caching, and instant scrubbing.',
  },
  {
    id: 'comp-5',
    title: 'IDENTITY SHIELDING & PRIVACY',
    status: 'CORE INFRASTRUCTURE',
    standardType: 'COMMUNICATION SECURITY',
    description: 'Reporter information is secured internally on Orbital while ensuring recipients receive purely anonymized threat telemetry.',
  },
];

export const INTEL_DISPATCHES: IntelDispatch[] = [
  {
    id: 'dispatch-004',
    dispatchNumber: 'DISPATCH 004',
    date: '12 AUG 2026',
    category: 'Neural Architecture',
    title: 'Inside the AI-Powered Brain³ OS: Fusing and Sorting African Threat Telemetry',
    excerpt: 'How the AI-powered Brain³ OS tokenizes chaotic multimodal sensor streams, decodes regional vernaculars, and sorts kinetic ambushes in sub-320ms.',
    readTime: '6 MIN READ',
    author: 'Tsidkenu Favour Benjamin — Systems Architecture',
    content: [
      'In high-stakes defensive operations across Africa, raw data is often noisy, fragmented, and asynchronous: an optical frame from a solar CCTV node, a micro-Doppler shockwave spike from an acoustic sensor, and a frantic 8-word voice report in Nigerian Pidgin.',
      'Generic consumer models fail catastrophically in this domain—they hallucinate, lack spatial-temporal geometric anchoring, and cannot parse localized African dialects or colloquial distress indicators.',
      'To solve this, we architected the AI-powered Brain³ OS: a specialized sovereign operating system engineered specifically for African geopolitical topography and kinetic threat triage.',
      'The AI-powered Brain³ OS orchestrates the real-time ingestion layer, converting raw satellite SAR passes, fixed-wing UAV thermals, nano-drone lidar, and offline LoRa packets into standardized spatial tokens. Brain³ OS then cross-correlates these tokens: verifying whether a reported gun attack matches acoustic shockwave timestamps and thermal heat anomalies within 320 milliseconds.',
      'The result is an intelligent, self-healing cognitive shield that sorts panic from authentic lethal danger—enabling instant, automated tactical dispatch without human bottlenecking.',
    ],
  },
  {
    id: 'dispatch-001',
    dispatchNumber: 'DISPATCH 001',
    date: '04 JUN 2026',
    category: 'Development Update',
    title: 'Multimodal Sensor Fusion: Integrating Satellite SAR, Tactical Drones, and Citizen Telemetry',
    excerpt: 'How we engineered a unified security intelligence pipeline using the AI-powered Brain³ OS that fuses orbital radar, solar CCTV, acoustic gunshot arrays, and civilian reports into a single sovereign threat matrix.',
    readTime: '5 MIN READ',
    author: 'Tsidkenu Favour Benjamin — Systems Architecture',
    content: [
      'In high-risk operating environments across Africa, the greatest deterrent to reporting an ongoing crime or violent incident is fear of reprisal. When citizens believe their identity will be revealed to recipients or adversaries, they stay silent.',
      'Our security intelligence framework addresses this directly: Orbital verifies and maintains user accounts securely on our end, but completely shields their identities from recipients and public alert streams.',
      'Simultaneously, we have unified this civilian stream with autonomous overhead vectors: synthetic aperture radar (SAR) satellite passes capable of penetrating cloud cover, tactical fixed-wing UAV patrols over interstate transit corridors, and solar-powered smart CCTV nodes.',
      'Laboratory and field benchmarks in Port Harcourt demonstrate end-to-end routing latency under 420 milliseconds across low-bandwidth 2G/3G network conditions and zero-internet LoRa mesh fallbacks.',
    ],
  },
  {
    id: 'dispatch-002',
    dispatchNumber: 'DISPATCH 002',
    date: '18 MAY 2026',
    category: 'Security Analysis',
    title: 'The Silent Cost: Analyzing the Failure Modes of Centralized Emergency Infrastructure in Africa',
    excerpt: 'A comprehensive investigation into why legacy 911/112 models fail in Sub-Saharan urban centers and how sovereign edge networks restore real-time defensive parity.',
    readTime: '6 MIN READ',
    author: 'Security Research Unit',
    content: [
      'Centralized dispatch systems rely on four critical assumptions: universal street addressing, high municipal dispatcher staffing, reliable telephony grid uptime, and institutional trust. In Sub-Saharan Africa, none of these conditions hold uniformly.',
      'When an incident occurs in areas like Port Harcourt, Aba, rural Kaduna, or suburban Ibadan, calls either bounce, queue indefinitely, or fail due to localized cellular congestion and grid collapses.',
      'Orbital Avtacha fundamentally shifts the paradigm from centralized hierarchical triage to decentralized, multimodal spatial consensus: fusing citizen reports with acoustic gunshot sensors, drone overwatch, and orbital satellites through the AI-powered Brain³ OS.',
      'By empowering verified localized responders with direct cryptographic threat telemetry, response latency drops from an average of 48 minutes to under 4 minutes.',
    ],
  },
  {
    id: 'dispatch-003',
    dispatchNumber: 'DISPATCH 003',
    date: '02 MAY 2026',
    category: 'Community',
    title: 'Field Notes from Port Harcourt: Community Pilots, Bush Paths, and Grassroots Intelligence',
    excerpt: 'Direct learnings from interviews with 120 community leaders, vigilante groups, transport union drivers, and residents on what sovereign security truly requires.',
    readTime: '5 MIN READ',
    author: 'Field Operations Team',
    content: [
      'Over the past 60 days, our field team conducted immersive listening sessions across diverse neighborhoods in Rivers State. We spoke with market associations, night security guards, interstate transport drivers, student unions, and community patrols.',
      'The consensus was unanimous: the intelligence is never missing. Every ambush corridor, illegal checkpoint, and armed robbery pattern is known by people on the ground 15 to 30 minutes before tragedy strikes.',
      'What was lacking was a unified, neutral, sovereign technical layer that could aggregate these discrete human observations—alongside solar CCTV, acoustic nodes, and drone coverage—into an actionable, non-corruptible threat matrix sorted by the AI-powered Brain³ OS.',
      'These findings directly informed our offline-first Bluetooth/LoRa mesh fallback protocols and the One-Touch SOS design.',
    ],
  },
];
